server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    hostname: service-registry
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/