server:
  port: 8000

zuul:
  ignoredServices: '*'
  prefix: /api    # 모든 요청의 접두사를 설정한다. 주울로 들어오는 모든 요청은 URL 내부에 리다이렉트할 때 주울이 제거하는 부분이 있어야 한다.
  routes:
    auth:
      path: /auth/**
      url: http://auth:8080
#      serviceId: auth     # bootstrap.properties에 설정한 값과 같아야 한다.
      stripPrefix: false
    user:
      path: /user/**
      url: http://user:8081
      #      serviceId: user
      stripPrefix: false
    post:
      path: /post/**
      url: http://post:8082
#      serviceId: post
      stripPrefix: false
    generator:
      path: /generator/**
      url: http://generator:8079
      #      serviceId: generator
      stripPrefix: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false  # 주울의 /trace 엔드포인트에 접속할 때 인증이 필요 없도록 설정


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/