server:
  port: 8000

zuul:
  ignored-services: '*'
  prefix: /api    # 모든 요청의 접두사를 설정한다. 주울로 들어오는 모든 요청은 URL 내부에 리다이렉트할 때 주울이 제거하는 부분이 있어야 한다.
  routes:
    auth:
      path: /auth/**
      serviceId: auth     # bootstrap.properties에 설정한 값과 같아야 한다.
      strip-prefix: false
    user:
      path: /user/**
      serviceId: user
      strip-prefix: false
    post:
      path: /post/**
      serviceId: post
      strip-prefix: false
    generator:
      path: /generator/**
      serviceId: generator
      strip-prefix: false

endpoints:
  routes:
    sensitive: false
  trace:
    sensitive: false  # 주울의 /trace 엔드포인트에 접속할 때 인증이 필요 없도록 설정


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  jwt:
    secret: hanjoo@sns!@#$;
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: root