server:
  port: 8000

zuul:
  prefix: /api    # 모든 요청의 접두사를 설정한다. 주울로 들어오는 모든 요청은 URL 내부에 리다이렉트할 때 주울이 제거하는 부분이 있어야 한다.
  routes:
    auth:
      path: /auth/**
      url: http://localhost:8080/auth
    user:
      path: /user/**
      url: http://localhost:8081/user
    post:
      path: /post/**
      url: http://localhost:8082/post

endpoints:
  trace:
    sensitive: false  # 주울의 /trace 엔드포인트에 접속할 때 인증이 필요 없도록 설정

ribbon:
  eureka:
    enabled: false